mysql:
  host: 127.0.0.1
  port: 3306
  config: "charset=utf8mb4&parseTime=True&loc=Local"
  db: gvb_db
  user: root
  password: mjh001127
  log_level: dev
logger:
  level: info
  prefix: '[gvb]'
  director: log
  show_line: true
  log_in_console: true #是否显示文件的路径
system:
  host: "0.0.0.0"
  port: 8080
  env: release
upload:
  size: 2
  path: uploads/file
site_info:
  created_at: "2023-02-12"
  bei_an: 备案
  title: 锦鸿的个人博客
  qq_image: http://www.fengfengzhidao.com/static/my/img/footer/qq.png
  version: 6.0.2
  email: jinhongm@student.unimelb.edu.au
  wechat_image: http://www.fengfengzhidao.com/static/my/img/footer/wechat.png
  name: 鸿知道
  job: back-ending-developer
  addr: Melbourne
  slogan: 锦鸿博客
  slogan_en: jmBlog
  web: http://www.fengfengzhidao.com/
  blibli_url: https://space.blibli.com/359151217
  gitee_url: https://gitee.com/fengfengzhidao
  github_url: https://github.com/fengfnegzhidao/
jwt:
  secret: xxx
  expires: 2
  issuer: 1234
qq:
  app-id: xx
  key: xx
  redirect: http://xx.xx.com/login?flag=qq
email:
  host: "SMTP"
  port: 0
  user: 438676972@qq.com
  password: ""
  default_from_email: ""
  use_ssl: true
  use_tls: false
qi_niu:
  enable: true
  access_key: QrLsOGJ8PO-KtpsLrHsdPhDgSBriTy78-B8Vq1x0
  secret_key: 2Nk0NTcCh2tQKfWngOyASqeGFpT2XYwpC0_y1uTj
  bucket: jmcalvinspace
  cdn: xx://xx.xx.com/
  zone: z2
  prefix: "gvb"
  size: 5

redis:
  ip : "127.0.0.1"
  port: 6379
  password: ""
  pool_size: 100

es:
  host : "http://127.0.0.1"
  port : 9200
  user :
  password :